name: Deploy API Docs to GitHub Pages

on:
  push:
    branches:
      - main-rest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Create openapi.yaml
        run: pnpm run openapi

      - name: Lint OpenAPI spec
        run: pnpm run validate-openapi 

      - name: Generate static API docs
        run: pnpm run static-api-doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
