name: Deployment

on:
  push:
    branches:
      - main-rest
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm setup
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
        shell: bash
        env:
          SHELL: /bin/bash

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generating prisma files
        run: pnpm prisma generate

      - name: Run lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Make build
        run: pnpm build

  deploy-db:
    runs-on: ubuntu-latest
    needs: test-and-build
    env:
      NODE_ENV: production
      ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
      ADMIN_EMAIL: ${{secrets.ADMIN_EMAIL}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm setup
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
        shell: bash
        env:
          SHELL: /bin/bash

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Write Aiven CA cert to file
        run: |
          mkdir -p prisma
          echo "${{ secrets.AIVEN_CA_CERT }}" > prisma/ca.pem 

      - name: Generating prisma files
        run: pnpm prisma generate

      - name: DB migration
        run: pnpm prisma migrate deploy

      - name: Seeding DB
        run: pnpm prisma db seed

  deploy:
    runs-on: ubuntu-latest
    needs: deploy-db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm setup
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
        shell: bash
        env:
          SHELL: /bin/bash

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generating prisma files
        run: pnpm prisma generate

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Read Node version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
      
      - name: Building a new docker image using Dockerfile.prod
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --provenance=false \
            -t docker-image:test \
            -f Dockerfile.prod \
            --build-arg NODE_VERSION="${NODE_VERSION}" \
            .

      - name: Tagging the docker image for AWS ECR
        run: docker tag docker-image:test ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}:latest

      - name: Logging into AWS ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Pushing Docker image to ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}:latest

      - name: Updating AWS Lambda function
        run: aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}:latest --publish
